# Chapter 1: Getting Know about the data

In [29]:
from configparser import DuplicateSectionError

import pandas as pd

Load Dataset

In [30]:
order_details = pd.read_csv(filepath_or_buffer="Data.tsv",sep="\t")
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### 1.1 Perform Initial Data Analysis

In [31]:
order_details.shape

(4622, 5)

In [32]:
order_details.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [33]:
order_details.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [34]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [35]:
order_details.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

### 1.2 Find items sold in the restaurant

In [36]:
order_details["item_name"].unique()

<StringArray>
[         'Chips and Fresh Tomato Salsa',
                                  'Izze',
                      'Nantucket Nectar',
 'Chips and Tomatillo-Green Chili Salsa',
                          'Chicken Bowl',
                         'Side of Chips',
                         'Steak Burrito',
                      'Steak Soft Tacos',
                   'Chips and Guacamole',
                  'Chicken Crispy Tacos',
                    'Chicken Soft Tacos',
                       'Chicken Burrito',
                           'Canned Soda',
                      'Barbacoa Burrito',
                      'Carnitas Burrito',
                         'Carnitas Bowl',
                         'Bottled Water',
 'Chips and Tomatillo Green Chili Salsa',
                         'Barbacoa Bowl',
                                 'Chips',
                    'Chicken Salad Bowl',
                            'Steak Bowl',
                   'Barbacoa Soft Tacos',
                        'Veggie Burrito',
                           'Veggie Bowl',
                    'Steak Crispy Tacos',
   'Chips and Tomatillo Red Chili Salsa',
                 'Barbacoa Crispy Tacos',
                     'Veggie Salad Bowl',
    'Chips and Roasted Chili-Corn Salsa',
    'Chips and Roasted Chili Corn Salsa',
                   'Carnitas Soft Tacos',
                         'Chicken Salad',
                     'Canned Soft Drink',
                      'Steak Salad Bowl',
                     '6 Pack Soft Drink',
   'Chips and Tomatillo-Red Chili Salsa',
                                  'Bowl',
                               'Burrito',
                          'Crispy Tacos',
                 'Carnitas Crispy Tacos',
                           'Steak Salad',
     'Chips and Mild Fresh Tomato Salsa',
                     'Veggie Soft Tacos',
                   'Carnitas Salad Bowl',
                   'Barbacoa Salad Bowl',
                                 'Salad',
                   'Veggie Crispy Tacos',
                          'Veggie Salad',
                        'Carnitas Salad']
Length: 50, dtype: str

### 1.3 Find top 5 selling items

In [37]:
order_details.groupby(by=["item_name"])['quantity'].sum().sort_values(ascending=False).head()

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

### 1.4 Find least 5 selling items

In [38]:
order_details.groupby(by=["item_name"])['quantity'].sum().sort_values().head()

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

# Chapter 2 - Data Cleaning

In [39]:
# format the price column
order_details['item_price'].str.replace('$',"").astype(float)

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [40]:
# store the formatted column into dataframe
order_details['item_price'] = order_details['item_price'].str.replace('$',"").astype(float)
order_details

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [88]:
print(order_details.dtypes)
order_details.describe(include='all')

order_id                int64
quantity                int64
item_name                 str
choice_description        str
item_price            float64
dtype: object

           order_id     quantity     item_name choice_description   item_price
count   4622.000000  4622.000000          4622               3376  4622.000000
unique          NaN          NaN            50               1043          NaN
top             NaN          NaN  Chicken Bowl        [Diet Coke]          NaN
freq            NaN          NaN           726                134          NaN
mean     927.254868     1.075725           NaN                NaN     7.464336
std      528.890796     0.410186           NaN                NaN     4.245557
min        1.000000     1.000000           NaN                NaN     1.090000
25%      477.250000     1.000000           NaN                NaN     3.390000
50%      926.000000     1.000000           NaN                NaN     8.750000
75%     1393.000000     1.000000           NaN                NaN     9.250000
max     1834.000000    15.000000           NaN                NaN    44.250000

# Chapter 3 - Pandas Data Structure

- 1D - Series
- 2D - Dataframe

In [46]:
students = ["Nithin","Shyam","Krish"]
studentsData = pd.Series(data=students,name="Students")
studentsData

0    Nithin
1     Shyam
2     Krish
Name: Students, dtype: str

In [47]:
marks = [78,67,98]
marksData = pd.Series(data=marks,name="Marks")
marksData

0    78
1    67
2    98
Name: Marks, dtype: int64

In [51]:
resultDict = {
    "Students": ["Nithin","Shyam","Krish"],
    "marks": [78,67,98]
}
resultDictPd = pd.DataFrame(data=resultDict)
resultDictPd

  Students  marks
0   Nithin     78
1    Shyam     67
2    Krish     98

# Chapter 4 - Filtering, Selection & Sorting

In [60]:
euro2012 = pd.read_csv("Euro_2012_stats_TEAM.csv")
euro2012

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [65]:
# filtering
euro2012_filtered = euro2012[["Team","Goals","Red Cards","Yellow Cards"]]
euro2012_filtered

                   Team  Goals  Red Cards  Yellow Cards
0               Croatia      4          0             9
1        Czech Republic      4          0             7
2               Denmark      4          0             4
3               England      5          0             5
4                France      3          0             6
5               Germany     10          0             4
6                Greece      5          1             9
7                 Italy      6          0            16
8           Netherlands      2          0             5
9                Poland      2          1             7
10             Portugal      6          0            12
11  Republic of Ireland      1          1             6
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

In [67]:
# Get top 5 teams received yellow cards
euro2012_filtered.sort_values(by="Yellow Cards",ascending=False)

                   Team  Goals  Red Cards  Yellow Cards
7                 Italy      6          0            16
10             Portugal      6          0            12
13                Spain     12          0            11
0               Croatia      4          0             9
6                Greece      5          1             9
14               Sweden      5          0             7
9                Poland      2          1             7
1        Czech Republic      4          0             7
12               Russia      5          0             6
11  Republic of Ireland      1          1             6
4                France      3          0             6
3               England      5          0             5
8           Netherlands      2          0             5
15              Ukraine      2          0             5
5               Germany     10          0             4
2               Denmark      4          0             4

In [68]:
# Get top 5 teams received red cards
euro2012_filtered.sort_values(by="Red Cards",ascending=False)

                   Team  Goals  Red Cards  Yellow Cards
6                Greece      5          1             9
9                Poland      2          1             7
11  Republic of Ireland      1          1             6
0               Croatia      4          0             9
3               England      5          0             5
4                France      3          0             6
2               Denmark      4          0             4
1        Czech Republic      4          0             7
7                 Italy      6          0            16
5               Germany     10          0             4
8           Netherlands      2          0             5
10             Portugal      6          0            12
12               Russia      5          0             6
13                Spain     12          0            11
14               Sweden      5          0             7
15              Ukraine      2          0             5

In [72]:
# Get teams scored only two goals
euro2012_filtered[euro2012_filtered["Goals"] == 2]

           Team  Goals  Red Cards  Yellow Cards
8   Netherlands      2          0             5
9        Poland      2          1             7
15      Ukraine      2          0             5

In [78]:
# Get teams with more than 5 yellow cards and sort by max goals
(euro2012_filtered[["Team","Yellow Cards","Goals"]][euro2012_filtered["Yellow Cards"] > 5]).sort_values("Goals",ascending=False)

                   Team  Yellow Cards  Goals
13                Spain            11     12
7                 Italy            16      6
10             Portugal            12      6
14               Sweden             7      5
12               Russia             6      5
6                Greece             9      5
0               Croatia             9      4
1        Czech Republic             7      4
4                France             6      3
9                Poland             7      2
11  Republic of Ireland             6      1

# Chapter 5 - Handling Missing Values

In [80]:
employeesInfo = pd.read_csv("Employee_data.csv")
employeesInfo

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

In [82]:
# Remove Duplicate
employeesInfo.drop_duplicates(inplace=True)
employeesInfo

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022

In [85]:
employeesInfo.isnull().sum()

Name          1
Age           1
Department    0
Salary        1
Join_Date     0
dtype: int64

In [87]:
employeesInfo.dropna(inplace=True)
employeesInfo

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023