# Import required libraries

In [183]:
import pandas as pd
import numpy as np
from datetime import datetime

# Load the datasets

In [184]:
salesData_2017 = pd.read_csv(r"Sales Data/Sales Transactions-2017.csv")
salesData_2018 = pd.read_csv(r"Sales Data/Sales Transactions-2018.csv")
salesData_2019 = pd.read_csv(r"Sales Data/Sales Transactions-2019.csv")

In [185]:
# combine all the data into one
bronzeSalesData = pd.concat([salesData_2017,salesData_2018,salesData_2019])
bronzeSalesData.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN

# Explore data for initial analysis

In [186]:
print(f"Dimensions: {bronzeSalesData.shape}")
print(f"Column Datatypes: \n{bronzeSalesData.dtypes}")
print(f"Columns:\t{bronzeSalesData.columns}")

Dimensions: (111206, 9)
Column Datatypes:
Date              str
Voucher           str
Party             str
Product           str
Qty               str
Rate              str
Gross             str
Disc              str
Voucher Amount    str
dtype: object
Columns:	Index(['Date', 'Voucher', 'Party', 'Product', 'Qty', 'Rate', 'Gross', 'Disc',
       'Voucher Amount'],
      dtype='str')

In [187]:
print(f"Null data info:\n{bronzeSalesData.isnull().sum()}")
print(f"Statistical analysis on bronze data\n")
bronzeSalesData.describe(include='all')

Null data info:
Date               12591
Voucher            12557
Party                 40
Product            12591
Qty                12557
Rate               12558
Gross              12558
Disc              105609
Voucher Amount     83646
dtype: int64
Statistical analysis on bronze data

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
count,98615,98649,111166,98615,98649,98648,98648,5597,27560
unique,836,10044,1994,867,546,1109,2548,371,7149
top,,,TP13,,100,,,,
freq,3053,3053,13056,3053,12528,3051,3053,3053,3053

#### Observations
The datatypes of the columns need to cleared for proper statistical information
- Date - to be updated as datetime
- Qty - to be updated as integer
- Rate, Gross, Disc, Voucher Amount - to be updated as float
- Disc - null can be updated as 0s

### Copy the raw data for initial cleaning

In [188]:
silverSalesData = bronzeSalesData.copy()

In [189]:
silverSalesData

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [190]:
silverSalesData = silverSalesData.replace(r"^\s*$", np.nan, regex=True) # to convert the empty string as proper NaN values
# convert all the numeric columns into numeric from string or object datatype
numeric_cols = [
    "Qty",
    "Rate",
    "Gross",
    "Disc",
    "Voucher Amount"
]

for col in numeric_cols:
    silverSalesData[col] = (
        silverSalesData[col]
        .astype("string")
        .str.replace(",", "", regex=False)
        .str.strip()
    )

    silverSalesData[col] = pd.to_numeric(
        silverSalesData[col],
        errors="coerce"
    )

In [191]:
# convert date into datetime datatype
silverSalesData["Date"] = pd.to_datetime(
    bronzeSalesData["Date"]
        .astype("string")
        .str.strip(),
    format="%d/%m/%Y",
    errors="coerce"
)
silverSalesData.dtypes

Date              datetime64[us]
Voucher                      str
Party                        str
Product                      str
Qty                      Float64
Rate                     Float64
Gross                    Float64
Disc                     Float64
Voucher Amount           Float64
dtype: object

In [192]:
silverSalesData.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,<NA>,13100.0
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,<NA>,<NA>
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,<NA>,30990.0
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,<NA>,<NA>
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,<NA>,<NA>

In [193]:
for col in numeric_cols:
    source_not_empty = bronzeSalesData[col].notna()
    conversion_failed = source_not_empty & silverSalesData[col].isna()

    print(
        f"{col}: {conversion_failed.sum()} "
        "non-empty values failed numeric conversion"
    )

Qty: 3051 non-empty values failed numeric conversion
Rate: 3051 non-empty values failed numeric conversion
Gross: 3053 non-empty values failed numeric conversion
Disc: 3053 non-empty values failed numeric conversion
Voucher Amount: 3053 non-empty values failed numeric conversion

In [194]:
def normalize_source(series):
    return (
        series
        .astype("string")
        .str.strip()
        .replace("", pd.NA)
    )

In [195]:
conversion_failure_masks = {}

for col in numeric_cols:
    source_normalized = normalize_source(bronzeSalesData[col])

    failure_mask = (
        source_normalized.notna()
        & silverSalesData[col].isna()
    )

    conversion_failure_masks[col] = failure_mask

    print(
        f"{col}: {failure_mask.sum()} genuine conversion failures"
    )

Qty: 0 genuine conversion failures
Rate: 0 genuine conversion failures
Gross: 0 genuine conversion failures
Disc: 0 genuine conversion failures
Voucher Amount: 0 genuine conversion failures

In [196]:
print("Minimum date:", silverSalesData["Date"].min())
print("Maximum date:", silverSalesData["Date"].max())
print("Invalid dates:", silverSalesData["Date"].isna().sum())

Minimum date: 2017-04-01 00:00:00
Maximum date: 2019-10-10 00:00:00
Invalid dates: 15644

In [197]:
missingSummary = pd.DataFrame({
    "Missing Count": silverSalesData.isna().sum(),
    "Missing Percentage": (
        silverSalesData.isna().mean() * 100
    ).round(2)
})

missingSummary.sort_values(
    "Missing Percentage",
    ascending=False
)

                Missing Count  Missing Percentage
Disc                   108662               97.71
Voucher Amount          86699               77.96
Date                    15644               14.07
Product                 15644               14.07
Voucher                 15610               14.04
Gross                   15611               14.04
Qty                     15608               14.04
Rate                    15609               14.04
Party                      40                0.04

In [198]:
critical_transaction_cols = [
    "Date",
    "Voucher",
    "Party",
    "Product",
    "Qty",
    "Rate",
    "Gross"
]

transaction_mask = (
    silverSalesData[critical_transaction_cols]
    .notna()
    .all(axis=1)
)

In [199]:
print("Total rows:", len(silverSalesData))
print("Valid transaction rows:", transaction_mask.sum())
print("Other rows:", (~transaction_mask).sum())

Total rows: 111206
Valid transaction rows: 95561
Other rows: 15645

In [200]:
rejectedSalesData = (
    silverSalesData.loc[~transaction_mask]
    .copy()
)

validSalesData = (
    silverSalesData.loc[transaction_mask]
    .copy()
)
rejectedSalesData[
    [
        "Date",
        "Voucher",
        "Party",
        "Product",
        "Qty",
        "Rate",
        "Gross",
        "Disc",
        "Voucher Amount"
    ]
].head(50)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
8,NaT,NaN,khader vali late en,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
9,NaT,NaN,try,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
11,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
12,NaT,NaN,DUMMY ENTRY,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
14,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
15,NaT,NaN,dummy entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
17,NaT,NaN,dummy entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
39,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
41,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
43,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
53,NaT,NaN,KR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
55,NaT,NaN,KR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
77,NaT,NaN,IC CENTRE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
79,NaT,NaN,LAKSHMIMEDICALS,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
81,NaT,NaN,LAKSHMIMEDICALS,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
96,NaT,NaN,AUTOLO,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
102,NaT,NaN,RAJASURESH KI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
104,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
106,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
108,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
110,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
112,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
114,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
116,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
122,NaT,NaN,CREDIT BILL,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
134,NaT,NaN,autolo,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
147,NaT,NaN,sriram srinivasulu,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
149,NaT,NaN,late entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
153,NaT,NaN,late entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
166,NaT,NaN,autolo,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
191,NaT,NaN,paid,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
193,NaT,NaN,credit bill,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
199,NaT,NaN,autolo,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
201,NaT,NaN,KUR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
203,NaT,NaN,KUR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
219,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
221,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
223,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
225,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
227,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
229,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
231,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
233,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
235,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
237,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
239,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
241,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
243,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
245,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
247,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>

In [201]:
rejectedSalesData.isna().sum()

Date              15644
Voucher           15610
Party                40
Product           15644
Qty               15608
Rate              15609
Gross             15611
Disc              15611
Voucher Amount    15611
dtype: int64

In [202]:
def get_missing_columns(row):
    return ", ".join(
        row.index[row.isna()].tolist()
    )

rejectedSalesData["Missing Columns"] = (
    rejectedSalesData.apply(
        get_missing_columns,
        axis=1
    )
)

rejectedSalesData[
    "Missing Columns"
].value_counts().head(20)

Missing Columns
Date, Voucher, Product, Qty, Rate, Gross, Disc, Voucher Amount           15602
Date, Party, Product                                                        34
Date, Voucher, Party, Product, Qty, Rate, Gross, Disc, Voucher Amount        6
Date, Voucher, Product, Gross, Disc, Voucher Amount                          2
Rate, Gross, Disc, Voucher Amount                                            1
Name: count, dtype: int64

## Distinguish comment rows from invalid transactions
A comment or continuation row typically has no date, voucher, product, quantity, rate, or gross.

In [203]:
comment_or_continuation_mask = (
    silverSalesData["Date"].isna()
    & silverSalesData["Voucher"].isna()
    & silverSalesData["Product"].isna()
    & silverSalesData["Qty"].isna()
    & silverSalesData["Rate"].isna()
    & silverSalesData["Gross"].isna()
)

A potentially invalid transaction has identifying information but is missing a critical numeric value:

In [204]:
invalid_transaction_mask = (
    silverSalesData["Date"].notna()
    & silverSalesData["Voucher"].notna()
    & silverSalesData["Product"].notna()
    & (
        silverSalesData["Qty"].isna()
        | silverSalesData["Rate"].isna()
        | silverSalesData["Gross"].isna()
    )
)

In [205]:
print(
    "Comments or continuation rows:",
    comment_or_continuation_mask.sum()
)

print(
    "Potential invalid transactions:",
    invalid_transaction_mask.sum()
)

Comments or continuation rows: 15608
Potential invalid transactions: 1

In [206]:
silverSalesData.loc[
    invalid_transaction_mask,
    [
        "Date",
        "Voucher",
        "Party",
        "Product",
        "Qty",
        "Rate",
        "Gross",
        "Disc",
        "Voucher Amount"
    ]
].head(50)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
43740,2018-03-05,Sal:9266,CUSTOMER,TIRML-BL-KG-17*23,2.0,<NA>,<NA>,<NA>,<NA>

In [207]:
silverSalesData.loc[
    comment_or_continuation_mask,
    [
        "Date",
        "Voucher",
        "Party",
        "Product",
        "Qty",
        "Rate",
        "Gross",
        "Disc",
        "Voucher Amount"
    ]
].head(50)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
8,NaT,NaN,khader vali late en,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
9,NaT,NaN,try,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
11,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
12,NaT,NaN,DUMMY ENTRY,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
14,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
15,NaT,NaN,dummy entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
17,NaT,NaN,dummy entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
39,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
41,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
43,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
53,NaT,NaN,KR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
55,NaT,NaN,KR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
77,NaT,NaN,IC CENTRE,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
79,NaT,NaN,LAKSHMIMEDICALS,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
81,NaT,NaN,LAKSHMIMEDICALS,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
96,NaT,NaN,AUTOLO,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
102,NaT,NaN,RAJASURESH KI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
104,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
106,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
108,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
110,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
112,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
114,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
116,NaT,NaN,LS VGIRI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
122,NaT,NaN,CREDIT BILL,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
134,NaT,NaN,autolo,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
147,NaT,NaN,sriram srinivasulu,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
149,NaT,NaN,late entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
153,NaT,NaN,late entry,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
166,NaT,NaN,autolo,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
191,NaT,NaN,paid,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
193,NaT,NaN,credit bill,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
199,NaT,NaN,autolo,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
201,NaT,NaN,KUR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
203,NaT,NaN,KUR,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
219,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
221,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
223,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
225,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
227,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
229,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
231,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
233,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
235,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
237,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
239,NaT,NaN,A STALL-CHITWEILI,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
241,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
243,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
245,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>
247,NaT,NaN,#NAME?,NaN,<NA>,<NA>,<NA>,<NA>,<NA>

### Create a row-status column
This provides an auditable cleaning process.

In [208]:
silverSalesData["Row Status"] = "Needs Review"

silverSalesData.loc[
    transaction_mask,
    "Row Status"
] = "Valid Transaction"

silverSalesData.loc[
    comment_or_continuation_mask,
    "Row Status"
] = "Comment or Continuation"

silverSalesData.loc[
    invalid_transaction_mask,
    "Row Status"
] = "Invalid Numeric Transaction"

In [209]:
silverSalesData["Row Status"].value_counts()

Row Status
Valid Transaction              95561
Comment or Continuation        15608
Needs Review                      36
Invalid Numeric Transaction        1
Name: count, dtype: int64

Then split the data:

In [210]:
rejectedSalesData = (
    silverSalesData[
        silverSalesData["Row Status"]
        != "Valid Transaction"
    ]
    .copy()
)

silverSalesData = (
    silverSalesData[
        silverSalesData["Row Status"]
        == "Valid Transaction"
    ]
    .copy()
)

silverSalesData.drop(
    columns=["Row Status"],
    inplace=True
)

In [211]:
silverSalesData.reset_index(
    drop=True,
    inplace=True
)

rejectedSalesData.reset_index(
    drop=True,
    inplace=True
)

In [212]:
# Fill missing discounts only in valid transaction rows
silverSalesData["Disc"] = (
    silverSalesData["Disc"].fillna(0)
)

print(
    "Missing discounts after filling:",
    silverSalesData["Disc"].isna().sum()
)

Missing discounts after filling: 0

### Clean text columns
Now standardize whitespace in the text fields.

In [213]:
text_cols = [
    "Voucher",
    "Party",
    "Product"
]

for col in text_cols:
    silverSalesData[col] = (
        silverSalesData[col]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

Preserve the original names while creating standardized versions for grouping:

Because these values might refer to the same party:
- Srinu
- SRINU
- srinu

In [214]:
silverSalesData["Party Standardized"] = (
    silverSalesData["Party"]
    .str.upper()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

silverSalesData["Product Standardized"] = (
    silverSalesData["Product"]
    .str.upper()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

## Analyze exact duplicate rows

In [215]:
exact_duplicate_count = (
    silverSalesData.duplicated().sum()
)

print(
    "Exact duplicate rows:",
    exact_duplicate_count
)

Exact duplicate rows: 275

In [216]:
duplicateRows = (
    silverSalesData[
        silverSalesData.duplicated(
            keep=False
        )
    ]
    .sort_values(
        by=[
            "Date",
            "Voucher",
            "Party",
            "Product"
        ]
    )
)

duplicateRows.head(50)

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount,Party Standardized,Product Standardized
1320,2017-04-12,Sal:439,TP13,Classic 250ml,100.0,23.0,2300.0,0.0,<NA>,TP13,CLASSIC 250ML
1335,2017-04-12,Sal:439,TP13,Classic 250ml,100.0,23.0,2300.0,0.0,<NA>,TP13,CLASSIC 250ML
1864,2017-04-17,Sal:443,SHAIK SIFULLA,CYCLE-BK-13*16,10.0,13.0,130.0,130.0,<NA>,SHAIK SIFULLA,CYCLE-BK-13*16
1873,2017-04-17,Sal:443,SHAIK SIFULLA,CYCLE-BK-13*16,10.0,13.0,130.0,130.0,<NA>,SHAIK SIFULLA,CYCLE-BK-13*16
1985,2017-04-17,Sal:552,TP13,Vishnu 300ml,100.0,27.5,2750.0,0.0,<NA>,TP13,VISHNU 300ML
1990,2017-04-17,Sal:552,TP13,Vishnu 300ml,100.0,27.5,2750.0,0.0,<NA>,TP13,VISHNU 300ML
2040,2017-04-18,Sal:497,Lakshmifancy,"TAPE ROLL 2"" 50MTRS",4.0,125.0,500.0,0.0,<NA>,LAKSHMIFANCY,"TAPE ROLL 2"" 50MTRS"
2041,2017-04-18,Sal:497,Lakshmifancy,"TAPE ROLL 2"" 50MTRS",4.0,125.0,500.0,0.0,<NA>,LAKSHMIFANCY,"TAPE ROLL 2"" 50MTRS"
2484,2017-04-21,Sal:599,SPM PROVISION-DAKKI,NO-00,1.0,150.0,150.0,0.0,<NA>,SPM PROVISION-DAKKI,NO-00
2485,2017-04-21,Sal:599,SPM PROVISION-DAKKI,NO-00,1.0,150.0,150.0,0.0,<NA>,SPM PROVISION-DAKKI,NO-00
2651,2017-04-22,Sal:642,Kvkc,SILVER POUCH 9*12,22.5,180.0,4050.0,0.0,<NA>,KVKC,SILVER POUCH 9*12
2659,2017-04-22,Sal:642,Kvkc,SILVER POUCH 9*12,22.5,180.0,4050.0,0.0,<NA>,KVKC,SILVER POUCH 9*12
3659,2017-04-29,Sal:877,TP13,Classic 300ml,100.0,24.5,2450.0,0.0,<NA>,TP13,CLASSIC 300ML
3665,2017-04-29,Sal:877,TP13,Classic 300ml,100.0,24.5,2450.0,0.0,<NA>,TP13,CLASSIC 300ML
4223,2017-05-03,Sal:1122,TP13,Classic 250ml,100.0,23.0,2300.0,0.0,<NA>,TP13,CLASSIC 250ML
4225,2017-05-03,Sal:1122,TP13,Classic 250ml,100.0,23.0,2300.0,0.0,<NA>,TP13,CLASSIC 250ML
4230,2017-05-03,Sal:1122,TP13,Classic 250ml,100.0,23.0,2300.0,0.0,<NA>,TP13,CLASSIC 250ML
4952,2017-05-08,Sal:1272,TP13,10*10 TIGER,10.0,132.0,1320.0,0.0,<NA>,TP13,10*10 TIGER
4954,2017-05-08,Sal:1272,TP13,10*10 TIGER,10.0,132.0,1320.0,0.0,<NA>,TP13,10*10 TIGER
4955,2017-05-08,Sal:1272,TP13,10*15 STAR-DCUT,10.0,86.0,860.0,0.0,<NA>,TP13,10*15 STAR-DCUT
4962,2017-05-08,Sal:1272,TP13,10*15 STAR-DCUT,10.0,86.0,860.0,0.0,<NA>,TP13,10*15 STAR-DCUT
4957,2017-05-08,Sal:1272,TP13,Vishnu 250ml,20.0,30.0,600.0,0.0,<NA>,TP13,VISHNU 250ML
4959,2017-05-08,Sal:1272,TP13,Vishnu 250ml,20.0,30.0,600.0,0.0,<NA>,TP13,VISHNU 250ML
5403,2017-05-11,Sal:1330,TP13,CLASSIC 250ML(100),80.0,28.5,2280.0,0.0,<NA>,TP13,CLASSIC 250ML(100)
5406,2017-05-11,Sal:1330,TP13,CLASSIC 250ML(100),80.0,28.5,2280.0,0.0,<NA>,TP13,CLASSIC 250ML(100)
5404,2017-05-11,Sal:1330,TP13,Vishnu 250ml,100.0,29.5,2950.0,0.0,<NA>,TP13,VISHNU 250ML
5407,2017-05-11,Sal:1330,TP13,Vishnu 250ml,100.0,29.5,2950.0,0.0,<NA>,TP13,VISHNU 250ML
5538,2017-05-12,Sal:1443,TP13,CLASSIC ENJOY(750),1.0,1320.0,1320.0,0.0,<NA>,TP13,CLASSIC ENJOY(750)
5548,2017-05-12,Sal:1443,TP13,CLASSIC ENJOY(750),1.0,1320.0,1320.0,0.0,<NA>,TP13,CLASSIC ENJOY(750)
5750,2017-05-13,Sal:1469,TP13,CLASSIC ENJOY(750),1.0,1320.0,1320.0,0.0,<NA>,TP13,CLASSIC ENJOY(750)
5760,2017-05-13,Sal:1469,TP13,CLASSIC ENJOY(750),1.0,1320.0,1320.0,0.0,<NA>,TP13,CLASSIC ENJOY(750)
5798,2017-05-15,Sal:1506,TP13,10*10 MORE,25.0,135.0,3375.0,0.0,<NA>,TP13,10*10 MORE
5820,2017-05-15,Sal:1506,TP13,10*10 MORE,25.0,135.0,3375.0,0.0,<NA>,TP13,10*10 MORE
5779,2017-05-15,Sal:1506,TP13,BLACK DOG-350ML,100.0,25.5,2550.0,0.0,<NA>,TP13,BLACK DOG-350ML
5818,2017-05-15,Sal:1506,TP13,BLACK DOG-350ML,100.0,25.5,2550.0,0.0,<NA>,TP13,BLACK DOG-350ML
5793,2017-05-15,Sal:1506,TP13,Classic 250ml,100.0,24.0,2400.0,0.0,<NA>,TP13,CLASSIC 250ML
5815,2017-05-15,Sal:1506,TP13,Classic 250ml,100.0,24.0,2400.0,0.0,<NA>,TP13,CLASSIC 250ML
5777,2017-05-15,Sal:1506,TP13,Classic 300ml,100.0,24.5,2450.0,0.0,<NA>,TP13,CLASSIC 300ML
5816,2017-05-15,Sal:1506,TP13,Classic 300ml,100.0,24.5,2450.0,0.0,<NA>,TP13,CLASSIC 300ML
5785,2017-05-15,Sal:1506,TP13,GANESH 10*12,100.0,11.0,1100.0,0.0,<NA>,TP13,GANESH 10*12
5808,2017-05-15,Sal:1506,TP13,GANESH 10*12,100.0,11.0,1100.0,0.0,<NA>,TP13,GANESH 10*12
6179,2017-05-17,Sal:1511,TP13,Classic 300ml,100.0,24.5,2450.0,0.0,<NA>,TP13,CLASSIC 300ML
6184,2017-05-17,Sal:1511,TP13,Classic 300ml,100.0,24.5,2450.0,0.0,<NA>,TP13,CLASSIC 300ML
6545,2017-05-19,Sal:1596,TP13,APPLE 300ML,100.0,28.0,2800.0,0.0,<NA>,TP13,APPLE 300ML
6548,2017-05-19,Sal:1596,TP13,APPLE 300ML,100.0,28.0,2800.0,0.0,<NA>,TP13,APPLE 300ML
6887,2017-05-22,Sal:1715,TP13,APPLE 300ML,100.0,28.0,2800.0,0.0,<NA>,TP13,APPLE 300ML
6895,2017-05-22,Sal:1715,TP13,APPLE 300ML,100.0,28.0,2800.0,0.0,<NA>,TP13,APPLE 300ML
7899,2017-05-30,Sal:1942,MADHUFANCY,"TAPE ROLL 2"" 50MTRS",1.0,120.0,120.0,0.0,<NA>,MADHUFANCY,"TAPE ROLL 2"" 50MTRS"
7900,2017-05-30,Sal:1942,MADHUFANCY,"TAPE ROLL 2"" 50MTRS",1.0,120.0,120.0,0.0,<NA>,MADHUFANCY,"TAPE ROLL 2"" 50MTRS"
8251,2017-06-02,Sal:2099,TP13,9*12 STAR-DCUT,5.0,100.0,500.0,0.0,<NA>,TP13,9*12 STAR-DCUT

In [217]:
# drop the duplicates
silverSalesData = (
    silverSalesData
    .drop_duplicates()
    .reset_index(drop=True)
)

## Validate Gross = Qty × Rate

In [218]:
silverSalesData["Calculated Gross"] = (
    silverSalesData["Qty"]
    * silverSalesData["Rate"]
)
silverSalesData["Gross Difference"] = (
    silverSalesData["Gross"]
    - silverSalesData["Calculated Gross"]
)
silverSalesData["Gross Valid"] = np.isclose(
    silverSalesData["Gross"],
    silverSalesData["Calculated Gross"],
    rtol=0,
    atol=0.01
)

In [219]:
silverSalesData[
    "Gross Valid"
].value_counts()

Gross Valid
True     95270
False       16
Name: count, dtype: int64

In [220]:
silverSalesData.loc[
    ~silverSalesData["Gross Valid"],
    [
        "Date",
        "Voucher",
        "Product",
        "Qty",
        "Rate",
        "Gross",
        "Calculated Gross",
        "Gross Difference"
    ]
].head(20)

,Date,Voucher,Product,Qty,Rate,Gross,Calculated Gross,Gross Difference
716,2017-04-07,Sal:146,CYCLE-BLU-10*12,1600.0,5.42,8670.0,8672.0,-2.0
16633,2017-08-16,Sal:4219,"TAPEROLL 2""",12.0,83.33,1000.0,999.96,0.04
19558,2017-09-08,Sal:4921,KAVITHA GOLD 10*12,1400.0,5.57,7800.0,7798.0,2.0
19613,2017-09-09,Sal:4913,KAVITHA GOLD 10*12,700.0,5.57,3900.0,3899.0,1.0
26660,2017-11-14,Sal:6592,GARBAGE BAGS-KGS,30.32,120.0,3639.0,3638.4,0.6
30083,2017-12-16,Sal:7487,DURGA 13*16 PINK,1600.0,8.94,14310.0,14304.0,6.0
33386,2018-01-17,Sal:8221,BAHUBALI WINE,110.0,22.73,2500.0,2500.3,-0.3
36138,2018-02-19,Sal:8933,KRISHNA 10*12 RED,930.0,6.21,5775.0,5775.3,-0.3
39648,2018-03-26,Sal:9841,KRISHNA 10*12 RED,1200.0,6.23,7480.0,7476.0,4.0
39649,2018-03-26,Sal:9841,KRISHNA 13*16 RED,640.0,13.06,8360.0,8358.4,1.6
48141,2018-06-09,Sal:1908,PAPER TEA,600.0,17.26,10353.0,10356.0,-3.0
57860,2018-09-05,Sal:4328,MILAN 4*5 POLY,1050.0,12.26,12867.75,12873.0,-5.25
75779,2019-03-08,Sal:8895,DONA-(108),3.0,1836.67,5510.0,5510.01,-0.01
80808,2019-04-24,Sal:622,BAHUBALI WINE,220.0,25.91,5700.0,5700.2,-0.2
81722,2019-05-03,Sal:885,LIDS-250ML,2000.0,0.01,10.0,20.0,-10.0
93097,2019-09-13,Sal:4263,SILV--250ML-LOOSE,100.0,1.26,125.5,126.0,-0.5

## Create basic validity flags

In [221]:
silverSalesData["Invalid Qty"] = (
    silverSalesData["Qty"] <= 0
)

silverSalesData["Invalid Rate"] = (
    silverSalesData["Rate"] < 0
)

silverSalesData["Invalid Gross"] = (
    silverSalesData["Gross"] < 0
)

silverSalesData["Invalid Discount"] = (
    silverSalesData["Disc"] < 0
)

In [222]:
validationSummary = pd.Series({
    "Invalid Qty": silverSalesData[
        "Invalid Qty"
    ].sum(),

    "Invalid Rate": silverSalesData[
        "Invalid Rate"
    ].sum(),

    "Invalid Gross": silverSalesData[
        "Invalid Gross"
    ].sum(),

    "Invalid Discount": silverSalesData[
        "Invalid Discount"
    ].sum(),

    "Gross Mismatch": (
        ~silverSalesData["Gross Valid"]
    ).sum()
})

validationSummary

Invalid Qty          0
Invalid Rate         0
Invalid Gross        0
Invalid Discount     0
Gross Mismatch      16
dtype: int64

In [223]:
# Missing discount means no recorded discount
silverSalesData["Disc"] = (
    silverSalesData["Disc"].fillna(0)
)

# Identify complete transaction rows
critical_transaction_cols = [
    "Date",
    "Voucher",
    "Party",
    "Product",
    "Qty",
    "Rate",
    "Gross"
]

transaction_mask = (
    silverSalesData[critical_transaction_cols]
    .notna()
    .all(axis=1)
)

print("Total rows:", len(silverSalesData))
print("Valid transaction rows:", transaction_mask.sum())
print("Rows requiring review:", (~transaction_mask).sum())

Total rows: 95286
Valid transaction rows: 95286
Rows requiring review: 0

In [224]:
silverSalesData.loc[
    ~transaction_mask,
    [
        "Date",
        "Voucher",
        "Party",
        "Product",
        "Qty",
        "Rate",
        "Gross",
        "Disc",
        "Voucher Amount"
    ]
].head(50)

Empty DataFrame
Columns: [Date, Voucher, Party, Product, Qty, Rate, Gross, Disc, Voucher Amount]
Index: []

## Inferences
- Main structural cleaning like numeric/date conversion, rejection of incomplete rows, text normalization, columns standardization, duplicate analysis/removal, gross validation
- The resulting dataset has 95,286 records with valid rows, while 16 gross mismatches, zero quantity etc., are present.
- The remaining business-level cleaning and recon needs to be done.

### Business-level Data Cleaning

Review the gross mismatches

In [225]:
grossMismatchData = (
    silverSalesData.loc[
        ~silverSalesData["Gross Valid"]
    ]
    .copy()
)

In [226]:
silverSalesData["Gross Difference Abs"] = (
    silverSalesData["Gross Difference"].abs()
)

silverSalesData["Gross Mismatch Type"] = np.select(
    [
        silverSalesData["Gross Valid"],
        silverSalesData["Gross Difference Abs"] <= 0.05,
        silverSalesData["Gross Difference Abs"] <= 1.00
    ],
    [
        "Exact / Within Tolerance",
        "Minor Rounding Difference",
        "Small Difference"
    ],
    default="Material Difference"
)

In [227]:
silverSalesData[
    "Gross Mismatch Type"
].value_counts()

Gross Mismatch Type
Exact / Within Tolerance     95270
Material Difference              8
Small Difference                 6
Minor Rounding Difference        2
Name: count, dtype: int64

In [228]:
silverSalesData.head()

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount,Party Standardized,Product Standardized,Calculated Gross,Gross Difference,Gross Valid,Invalid Qty,Invalid Rate,Invalid Gross,Invalid Discount,Gross Difference Abs,Gross Mismatch Type
0,2017-04-01,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2.0,1690.0,3380.0,0.0,13100.0,SOLANKI PLASTICS,DONA-VAI-9100,3380.0,0.0,True,False,False,False,False,0.0,Exact / Within Tolerance
1,2017-04-01,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,<NA>,SOLANKI PLASTICS,LITE FOAM(1200),9720.0,0.0,True,False,False,False,False,0.0,Exact / Within Tolerance
2,2017-04-01,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500.0,23.0,11500.0,0.0,30990.0,SARNESWARA TRADERS,VISHNU CHOTA WINE,11500.0,0.0,True,False,False,False,False,0.0,Exact / Within Tolerance
3,2017-04-01,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6.0,1620.0,9720.0,0.0,<NA>,SARNESWARA TRADERS,LITE FOAM(1200),9720.0,0.0,True,False,False,False,False,0.0,Exact / Within Tolerance
4,2017-04-01,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5.0,1690.0,8450.0,0.0,<NA>,SARNESWARA TRADERS,DONA-VAI-9100,8450.0,0.0,True,False,False,False,False,0.0,Exact / Within Tolerance

In [229]:
grossReviewData = (
    silverSalesData.loc[
        silverSalesData["Gross Mismatch Type"]
        != "Exact / Within Tolerance"
    ]
    .copy()
)

In [230]:
grossReviewData.shape

(16, 20)

In [231]:
grossReviewData = (
    grossReviewData
    .sort_values(
        "Gross Difference Abs",
        ascending=False
    )
)

grossReviewData[
    [
        "Date",
        "Voucher",
        "Party",
        "Product",
        "Qty",
        "Rate",
        "Gross",
        "Calculated Gross",
        "Gross Difference",
        "Gross Difference Abs",
        "Gross Mismatch Type"
    ]
]

,Date,Voucher,Party,Product,Qty,Rate,Gross,Calculated Gross,Gross Difference,Gross Difference Abs,Gross Mismatch Type
81722,2019-05-03,Sal:885,K.SRIHARI,LIDS-250ML,2000.0,0.01,10.0,20.0,-10.0,10.0,Material Difference
30083,2017-12-16,Sal:7487,SANKAR,DURGA 13*16 PINK,1600.0,8.94,14310.0,14304.0,6.0,6.0,Material Difference
57860,2018-09-05,Sal:4328,SVP-BUCHHI,MILAN 4*5 POLY,1050.0,12.26,12867.75,12873.0,-5.25,5.25,Material Difference
39648,2018-03-26,Sal:9841,KVK,KRISHNA 10*12 RED,1200.0,6.23,7480.0,7476.0,4.0,4.0,Material Difference
48141,2018-06-09,Sal:1908,SVP-BUCHHI,PAPER TEA,600.0,17.26,10353.0,10356.0,-3.0,3.0,Material Difference
716,2017-04-07,Sal:146,TEACHER,CYCLE-BLU-10*12,1600.0,5.42,8670.0,8672.0,-2.0,2.0,Material Difference
19558,2017-09-08,Sal:4921,BABASTORES,KAVITHA GOLD 10*12,1400.0,5.57,7800.0,7798.0,2.0,2.0,Material Difference
39649,2018-03-26,Sal:9841,KVK,KRISHNA 13*16 RED,640.0,13.06,8360.0,8358.4,1.6,1.6,Material Difference
19613,2017-09-09,Sal:4913,KHAN AND KHAN PLAST,KAVITHA GOLD 10*12,700.0,5.57,3900.0,3899.0,1.0,1.0,Small Difference
26660,2017-11-14,Sal:6592,KRISHNAPATNAM PORT,GARBAGE BAGS-KGS,30.32,120.0,3639.0,3638.4,0.6,0.6,Small Difference
93097,2019-09-13,Sal:4263,HOTEL NTC-NELLORE,SILV--250ML-LOOSE,100.0,1.26,125.5,126.0,-0.5,0.5,Small Difference
33386,2018-01-17,Sal:8221,KISHORE-NAVABPET,BAHUBALI WINE,110.0,22.73,2500.0,2500.3,-0.3,0.3,Small Difference
36138,2018-02-19,Sal:8933,KVK,KRISHNA 10*12 RED,930.0,6.21,5775.0,5775.3,-0.3,0.3,Small Difference
80808,2019-04-24,Sal:622,Kalyani Fruit Juice,BAHUBALI WINE,220.0,25.91,5700.0,5700.2,-0.2,0.2,Small Difference
16633,2017-08-16,Sal:4219,TVT-CHITWELI,"TAPEROLL 2""",12.0,83.33,1000.0,999.96,0.04,0.04,Minor Rounding Difference
75779,2019-03-08,Sal:8895,SURYA TRADERS,DONA-(108),3.0,1836.67,5510.0,5510.01,-0.01,0.01,Minor Rounding Difference

Keeping all these records with flags for later review

In [232]:
# creatin overall data quality status
silverSalesData["Quality Status"] = np.where(
    silverSalesData["Gross Mismatch Type"]
    == "Exact / Within Tolerance",
    "Passed",
    "Review Gross Difference"
)

In [233]:
silverSalesData["Quality Status"].value_counts()

Quality Status
Passed                     95270
Review Gross Difference       16
Name: count, dtype: int64

In [234]:
# assign priority for review process
priority_mapping = {
    "Exact / Within Tolerance": "No Review",
    "Minor Rounding Difference": "Low",
    "Small Difference": "Medium",
    "Material Difference": "High"
}

silverSalesData["Review Priority"] = (
    silverSalesData[
        "Gross Mismatch Type"
    ]
    .map(priority_mapping)
)

In [235]:
silverSalesData[
    "Review Priority"
].value_counts()

Review Priority
No Review    95270
High             8
Medium           6
Low              2
Name: count, dtype: int64

Gross was validated against Qty × Rate using an absolute tolerance of 0.01. Of the 95,286 cleaned transaction rows, 95,270 were within tolerance. Sixteen records exceeded the tolerance, consisting of two minor rounding differences, six small differences, and eight material differences. These records were retained in the Silver dataset with quality and review-priority flags because the available data does not establish whether Gross, Rate, or another transaction rule is responsible for the variance.

#### Cleaning the voucher level reconcilation
- for that first let us create a meaningful transaction id

In [236]:
silverSalesData["Transaction Key"] = (
    silverSalesData["Date"].dt.strftime("%Y%m%d")
    + "_"
    + silverSalesData["Voucher"].astype("string")
    + "_"
    + silverSalesData["Party Standardized"]
)

In [237]:
print(
    "Unique transaction keys:",
    silverSalesData["Transaction Key"].nunique()
)

print(
    "Total transaction lines:",
    len(silverSalesData)
)

Unique transaction keys: 24474
Total transaction lines: 95286

Check whether one transaction key contains multiple party names:

In [238]:
transactionKeyCheck = (
    silverSalesData
    .groupby("Transaction Key")
    .agg(
        Party_Count=("Party Standardized", "nunique"),
        Date_Count=("Date", "nunique"),
        Voucher_Count=("Voucher", "nunique")
    )
)

transactionKeyCheck[
    (transactionKeyCheck["Party_Count"] > 1)
    | (transactionKeyCheck["Date_Count"] > 1)
    | (transactionKeyCheck["Voucher_Count"] > 1)
]

Empty DataFrame
Columns: [Party_Count, Date_Count, Voucher_Count]
Index: []

#### Voucher summary

In [239]:
voucherSummary = (
    silverSalesData
    .groupby(
        [
            "Transaction Key",
            "Date",
            "Voucher",
            "Party Standardized"
        ],
        as_index=False
    )
    .agg(
        Line_Count=("Product", "size"),
        Product_Count=("Product Standardized", "nunique"),
        Quantity_Total=("Qty", "sum"),
        Gross_Total=("Gross", "sum"),
        Discount_Total=("Disc", "sum"),

        # Count how many rows contain a reported voucher amount
        Voucher_Amount_Count=("Voucher Amount", "count"),

        # Get the minimum and maximum to detect differing totals
        Voucher_Amount_Min=("Voucher Amount", "min"),
        Voucher_Amount_Max=("Voucher Amount", "max")
    )
)

#### Derive the reported voucher amount
- If one voucher total is recorded on only one transaction line, minimum and maximum will be the same.

In [240]:
voucherSummary["Reported Voucher Amount"] = (
    voucherSummary["Voucher_Amount_Max"]
)

In [241]:
voucherSummary["Calculated Net Amount"] = (
    voucherSummary["Gross_Total"]
    - voucherSummary["Discount_Total"]
)

In [242]:
voucherSummary["Voucher Difference"] = (
    voucherSummary["Reported Voucher Amount"]
    - voucherSummary["Calculated Net Amount"]
)

voucherSummary["Voucher Difference Abs"] = (
    voucherSummary["Voucher Difference"].abs()
)

#### Identify missing or inconsistent voucher totals

In [243]:
voucherSummary["Voucher Amount Missing"] = (
    voucherSummary["Reported Voucher Amount"].isna()
)
voucherSummary["Multiple Voucher Amount Entries"] = (
    voucherSummary["Voucher_Amount_Count"] > 1
)

In [244]:
voucherSummary["Conflicting Voucher Amounts"] = (
    voucherSummary["Voucher_Amount_Count"].gt(1)
    & ~np.isclose(
        voucherSummary["Voucher_Amount_Min"],
        voucherSummary["Voucher_Amount_Max"],
        rtol=0,
        atol=0.01,
        equal_nan=True
    )
)

#### Validate the voucher amount

In [245]:
voucherSummary["Voucher Valid"] = np.isclose(
    voucherSummary["Reported Voucher Amount"],
    voucherSummary["Calculated Net Amount"],
    rtol=0,
    atol=1.00,
    equal_nan=False
)

#### Classisifcation of the reconcilation results

In [246]:
voucherSummary["Voucher Reconciliation Status"] = np.select(
    [
        voucherSummary["Voucher Amount Missing"]
        .fillna(False)
        .to_numpy(dtype=bool),

        voucherSummary["Conflicting Voucher Amounts"]
        .fillna(False)
        .to_numpy(dtype=bool),

        voucherSummary["Voucher Valid"]
        .fillna(False)
        .to_numpy(dtype=bool),

        voucherSummary["Voucher Difference Abs"]
        .le(5.00)
        .fillna(False)
        .to_numpy(dtype=bool),

        voucherSummary["Voucher Difference Abs"]
        .le(20.00)
        .fillna(False)
        .to_numpy(dtype=bool)
    ],
    [
        "Missing Reported Voucher Amount",
        "Conflicting Reported Voucher Amounts",
        "Reconciled",
        "Small Difference",
        "Moderate Difference"
    ],
    default="Material Difference"
)

In [247]:
voucherSummary[
    "Voucher Reconciliation Status"
].value_counts(dropna=False)

Voucher Reconciliation Status
Reconciled                         10175
Material Difference                 8788
Moderate Difference                 5504
Small Difference                       6
Missing Reported Voucher Amount        1
Name: count, dtype: int64

In [248]:
print(
    "Missing classifications:",
    voucherSummary[
        "Voucher Reconciliation Status"
    ].isna().sum()
)

Missing classifications: 0

In [249]:
print(
    voucherSummary[
        "Voucher Difference Abs"
    ].le(5.00).dtype
)

print(
    small_difference_condition.dtype
)

boolean
bool

In [252]:
# create review priority of voucher recon
voucherPriorityMapping = {
    "Reconciled": "No Review",
    "Small Difference": "Low",
    "Moderate Difference": "Medium",
    "Material Difference": "High",
    "Missing Reported Voucher Amount": "High",
    "Conflicting Reported Voucher Amounts": "High"
}

voucherSummary["Review Priority"] = (
    voucherSummary[
        "Voucher Reconciliation Status"
    ]
    .map(voucherPriorityMapping)
)

In [253]:
voucherReconciliationSummary = (
    voucherSummary[
        "Voucher Reconciliation Status"
    ]
    .value_counts(dropna=False)
    .rename_axis("Reconciliation Status")
    .reset_index(name="Voucher Count")
)

voucherReconciliationSummary["Percentage"] = (
    voucherReconciliationSummary["Voucher Count"]
    / len(voucherSummary)
    * 100
).round(2)

voucherReconciliationSummary

             Reconciliation Status  Voucher Count  Percentage
0                       Reconciled          10175       41.57
1              Material Difference           8788       35.91
2              Moderate Difference           5504       22.49
3                 Small Difference              6        0.02
4  Missing Reported Voucher Amount              1        0.00

In [254]:
voucherSummary[
    "Review Priority"
].value_counts(dropna=False)

Review Priority
No Review    10175
High          8789
Medium        5504
Low              6
Name: count, dtype: int64

In [255]:
materialVoucherMismatchData = (
    voucherSummary.loc[
        voucherSummary[
            "Voucher Reconciliation Status"
        ] == "Material Difference"
    ]
    .sort_values(
        "Voucher Difference Abs",
        ascending=False
    )
)

materialVoucherMismatchData.head(30)

,Transaction Key,Date,Voucher,Party Standardized,Line_Count,Product_Count,Quantity_Total,Gross_Total,Discount_Total,Voucher_Amount_Count,...,Reported Voucher Amount,Calculated Net Amount,Voucher Difference,Voucher Difference Abs,Voucher Amount Missing,Multiple Voucher Amount Entries,Conflicting Voucher Amounts,Voucher Valid,Voucher Reconciliation Status,Review Priority
10656,20180426_Sal:648_SEKHAR MARKET,2018-04-26,Sal:648,SEKHAR MARKET,6,6,12490.0,29165.0,0.0,1,...,45725.0,29165.0,16560.0,16560.0,False,False,False,False,Material Difference,High
24148,20190927_Sal:4608_SEKHAR MARKET,2019-09-27,Sal:4608,SEKHAR MARKET,3,1,180.0,50400.0,0.0,1,...,66000.0,50400.0,15600.0,15600.0,False,False,False,False,Material Difference,High
19923,20190413_Sal:406_TP13,2019-04-13,Sal:406,TP13,32,32,4872.0,83461.0,0.0,1,...,97032.0,83461.0,13571.0,13571.0,False,False,False,False,Material Difference,High
1407,20170515_Sal:1506_TP13,2017-05-15,Sal:1506,TP13,54,47,8016.0,152007.0,0.0,1,...,163882.0,152007.0,11875.0,11875.0,False,False,False,False,Material Difference,High
20600,20190508_Sal:1049_TP13,2019-05-08,Sal:1049,TP13,13,12,881.0,32230.0,0.0,1,...,43625.0,32230.0,11395.0,11395.0,False,False,False,False,Material Difference,High
19808,20190409_Sal:263_TP13,2019-04-09,Sal:263,TP13,31,31,7934.0,93318.0,0.0,1,...,104144.0,93318.0,10826.0,10826.0,False,False,False,False,Material Difference,High
17109,20181226_Sal:7272_TP13,2018-12-26,Sal:7272,TP13,63,53,8429.0,173741.0,0.0,1,...,183461.0,173741.0,9720.0,9720.0,False,False,False,False,Material Difference,High
6067,20171023_Sal:6338_TP13,2017-10-23,Sal:6338,TP13,32,32,5804.0,84625.0,0.0,1,...,93975.0,84625.0,9350.0,9350.0,False,False,False,False,Material Difference,High
11920,20180609_Sal:2067_TP13,2018-06-09,Sal:2067,TP13,20,20,3876.0,63641.0,0.0,1,...,72761.0,63641.0,9120.0,9120.0,False,False,False,False,Material Difference,High
11767,20180604_Sal:2052_TP13,2018-06-04,Sal:2052,TP13,22,20,5003.0,75332.0,0.0,1,...,83782.0,75332.0,8450.0,8450.0,False,False,False,False,Material Difference,High
20248,20190425_Sal:684_TP13,2019-04-25,Sal:684,TP13,25,21,4666.2,71101.0,0.0,1,...,79165.0,71101.0,8064.0,8064.0,False,False,False,False,Material Difference,High
19492,20190329_Sal:9568_TP13,2019-03-29,Sal:9568,TP13,11,10,1590.0,33895.0,0.0,1,...,41959.0,33895.0,8064.0,8064.0,False,False,False,False,Material Difference,High
4971,20170911_Sal:5063_TP13,2017-09-11,Sal:5063,TP13,27,27,1659.0,54700.0,0.0,1,...,62675.0,54700.0,7975.0,7975.0,False,False,False,False,Material Difference,High
18888,20190309_Sal:8923_SEKHAR MARKET,2019-03-09,Sal:8923,SEKHAR MARKET,3,1,26000.0,33800.0,0.0,1,...,41600.0,33800.0,7800.0,7800.0,False,False,False,False,Material Difference,High
13803,20180818_Sal:3820_TP13,2018-08-18,Sal:3820,TP13,21,21,3810.0,64509.0,0.0,1,...,71469.0,64509.0,6960.0,6960.0,False,False,False,False,Material Difference,High
19300,20190322_Sal:9345_TP13,2019-03-22,Sal:9345,TP13,39,36,9622.0,147035.0,0.0,1,...,153975.0,147035.0,6940.0,6940.0,False,False,False,False,Material Difference,High
11325,20180518_Sal:1511_TP13,2018-05-18,Sal:1511,TP13,16,15,2765.0,38274.0,0.0,1,...,45134.0,38274.0,6860.0,6860.0,False,False,False,False,Material Difference,High
12053,20180614_Sal:2115_TP13,2018-06-14,Sal:2115,TP13,36,32,7517.5,92617.0,0.0,1,...,98947.0,92617.0,6330.0,6330.0,False,False,False,False,Material Difference,High
10914,20180504_Sal:931_TP13,2018-05-04,Sal:931,TP13,6,6,276.0,11085.0,280.0,1,...,16925.0,10805.0,6120.0,6120.0,False,False,False,False,Material Difference,High
7223,20171207_Sal:7256_SK SALIM-PDKR,2017-12-07,Sal:7256,SK SALIM-PDKR,2,2,50.0,4000.0,7020.0,1,...,3020.0,-3020.0,6040.0,6040.0,False,False,False,False,Material Difference,High
9847,20180328_Sal:10026_TP13,2018-03-28,Sal:10026,TP13,17,17,1336.0,37610.0,0.0,1,...,43635.0,37610.0,6025.0,6025.0,False,False,False,False,Material Difference,High
16846,20181215_Sal:6911_TP13,2018-12-15,Sal:6911,TP13,23,21,3183.0,62075.0,0.0,1,...,67975.0,62075.0,5900.0,5900.0,False,False,False,False,Material Difference,High
17069,20181225_Sal:7267_TP13,2018-12-25,Sal:7267,TP13,21,20,1245.0,39300.0,0.0,1,...,45120.0,39300.0,5820.0,5820.0,False,False,False,False,Material Difference,High
11421,20180522_Sal:1493_TP13,2018-05-22,Sal:1493,TP13,18,18,3082.0,46460.0,0.0,1,...,52200.0,46460.0,5740.0,5740.0,False,False,False,False,Material Difference,High
18602,20190226_Sal:8797_TP13,2019-02-26,Sal:8797,TP13,22,21,2346.0,41360.0,0.0,1,...,47085.0,41360.0,5725.0,5725.0,False,False,False,False,Material Difference,High
19523,20190330_Sal:9570_TP13,2019-03-30,Sal:9570,TP13,15,15,2046.0,36545.0,0.0,1,...,42040.0,36545.0,5495.0,5495.0,False,False,False,False,Material Difference,High
12027,20180613_Sal:2073_TP13,2018-06-13,Sal:2073,TP13,23,21,2183.0,47097.0,0.0,1,...,52517.0,47097.0,5420.0,5420.0,False,False,False,False,Material Difference,High
17245,20181231_Sal:7304_TP13,2018-12-31,Sal:7304,TP13,17,15,4915.0,51340.0,0.0,1,...,56730.0,51340.0,5390.0,5390.0,False,False,False,False,Material Difference,High
4331,20170819_Sal:4402_TP13,2017-08-19,Sal:4402,TP13,19,18,5741.0,47055.0,0.0,1,...,52295.0,47055.0,5240.0,5240.0,False,False,False,False,Material Difference,High
1310,20170511_Sal:1330_TP13,2017-05-11,Sal:1330,TP13,7,6,875.0,15280.0,0.0,1,...,20510.0,15280.0,5230.0,5230.0,False,False,False,False,Material Difference,High

Inspect missing voucher amounts

In [256]:
missingVoucherAmountData = (
    voucherSummary.loc[
        voucherSummary[
            "Voucher Amount Missing"
        ]
    ]
    .copy()
)

missingVoucherAmountData[
    [
        "Date",
        "Voucher",
        "Party Standardized",
        "Line_Count",
        "Gross_Total",
        "Discount_Total",
        "Calculated Net Amount"
    ]
].head(30)

,Date,Voucher,Party Standardized,Line_Count,Gross_Total,Discount_Total,Calculated Net Amount
9166,2018-03-02,Sal:9204,SB.ENTERPRISES,1,12100.0,12100.0,0.0

In [257]:
voucherStatusColumns = [
    "Transaction Key",
    "Calculated Net Amount",
    "Reported Voucher Amount",
    "Voucher Difference",
    "Voucher Reconciliation Status",
    "Review Priority"
]

silverSalesData = silverSalesData.merge(
    voucherSummary[voucherStatusColumns],
    on="Transaction Key",
    how="left",
    validate="many_to_one"
)

In [258]:
print(
    "Silver rows after voucher merge:",
    len(silverSalesData)
)

Silver rows after voucher merge: 95286

Final quality checks

In [259]:
assert (
    voucherSummary["Transaction Key"].is_unique
), "Voucher summary contains duplicate transaction keys"

In [260]:
assert (
    silverSalesData[
        "Voucher Reconciliation Status"
    ].notna().all()
), "Some Silver rows did not receive a reconciliation status"

In [261]:
print(
    "Total vouchers:",
    len(voucherSummary)
)

print(
    "Reconciled vouchers:",
    voucherSummary["Voucher Valid"].sum()
)

print(
    "Vouchers requiring review:",
    (
        voucherSummary[
            "Voucher Reconciliation Status"
        ] != "Reconciled"
    ).sum()
)

Total vouchers: 24474
Reconciled vouchers: 10175
Vouchers requiring review: 14299