# List Comprehension

#### Example 1

In [24]:
numbers = [1, 2, 3, 4, 5, 6]

even_squares = [
    number ** 2
    for number in numbers
    if number % 2 == 0
]

print(even_squares)

[4, 16, 36]

In [25]:
gross_sales = [
    3380.00,
    9720.00,
    11500.00,
    8450.00,
    1320.00
]

high_value_sales = [
    sale
    for sale in gross_sales
    if sale >= 5000
]

print(high_value_sales)

[9720.0, 11500.0, 8450.0]

# Lambda function

In [26]:
cube = lambda number: number ** 3

print(cube(5))

125

In [27]:
increased_sales = list(
    map(
        lambda sale: round(sale * 1.05, 2),
        gross_sales
    )
)

print(increased_sales)

[3549.0, 10206.0, 12075.0, 8872.5, 1386.0]

In [28]:
high_value_sales = list(
    filter(
        lambda sale: sale >= 5000,
        gross_sales
    )
)

print(high_value_sales)

[9720.0, 11500.0, 8450.0]

In [29]:
high_value_sales = list(
    map(
        lambda sale: sale >= 5000,
        gross_sales
    )
)

print(high_value_sales)

[False, True, True, True, False]

The map only returned the boolean output on the condition. To get the actual values that are True for the condition can be produced by filter

In [30]:
from functools import reduce

In [31]:
total_gross_sales = reduce(
    lambda total, sale: total + sale,
    gross_sales,
    0
)

print(total_gross_sales)

34370.0

# Merging Dataframes

The row merging demonstrated on the data cleaning task. Now showing merging by columns.

In [32]:
import pandas as pd

In [33]:
employees = {
    "emp_id":["ab12390","bd78238","hj75634","yu87349","po09347"],
    "emp_designation":["Senior Associate","Lead","Associate","Lead","Delivery Head"],
    "emp_age":[32,35,28,33,39],
    "emp_deptId":["HR","ET","ET","SM","ET"],
    "emp_salary":[45000,150000,100000,135000,295000]
}

dept = {
    "dept_id":["HR","ET","SM"],
    "dept_name":["Human Resources","Engineering & Technology","Sales Management"],
    "dept_reporting":["CFO","CTO","CEO"]
}

In [34]:
employees_data = pd.DataFrame(data=employees)
employees_data

    emp_id   emp_designation  emp_age emp_deptId  emp_salary
0  ab12390  Senior Associate       32         HR       45000
1  bd78238              Lead       35         ET      150000
2  hj75634         Associate       28         ET      100000
3  yu87349              Lead       33         SM      135000
4  po09347     Delivery Head       39         ET      295000

In [35]:
dept_data = pd.DataFrame(data=dept)
dept_data

  dept_id                 dept_name dept_reporting
0      HR           Human Resources            CFO
1      ET  Engineering & Technology            CTO
2      SM          Sales Management            CEO

In [36]:
data_merged = pd.merge(
    employees_data,
    dept_data,how="inner",
    left_on="emp_deptId",
    right_on="dept_id"
)
data_merged

,emp_id,emp_designation,emp_age,emp_deptId,emp_salary,dept_id,dept_name,dept_reporting
0,ab12390,Senior Associate,32,HR,45000,HR,Human Resources,CFO
1,bd78238,Lead,35,ET,150000,ET,Engineering & Technology,CTO
2,hj75634,Associate,28,ET,100000,ET,Engineering & Technology,CTO
3,yu87349,Lead,33,SM,135000,SM,Sales Management,CEO
4,po09347,Delivery Head,39,ET,295000,ET,Engineering & Technology,CTO

In [37]:
data_merged[["emp_id","emp_designation","dept_reporting"]]

    emp_id   emp_designation dept_reporting
0  ab12390  Senior Associate            CFO
1  bd78238              Lead            CTO
2  hj75634         Associate            CTO
3  yu87349              Lead            CEO
4  po09347     Delivery Head            CTO