# Python Data Structures

### Python Datatype - List

In [20]:
# Add products to the cart

cart = [] # intialize empty cart (list)
cart.append('Apple') # add Apple to the cart
cart.append('Banana')

# print the items in the cart
print(f"Items in the cart: {cart}")

# clear the cart
print("Clearing the cart...")
cart.clear()
print(f"Items in the cart: {cart}")

Items in the cart: ['Apple', 'Banana']
Clearing the cart...
Items in the cart: []

In [1]:
# Add new products to the inventory
inventory = ['Apple', 'Banana', 'Orange']
new_products = ['Mango', 'Kiwi']
print("Items before adding new products to the inventory: ", inventory)
inventory.extend(new_products)
print("Items after adding new products to the inventory: ", inventory)

Items before adding new products to the inventory:  ['Apple', 'Banana', 'Orange']
Items after adding new products to the inventory:  ['Apple', 'Banana', 'Orange', 'Mango', 'Kiwi']

In [10]:
# insert an order in a specific position in the list
orders = ["Order1", "Order2", "Order3"]

orders.insert(1, "Order1.b")
print("Inserted order. Updated orders list: ",orders)
orders.insert(5, "Order5") #adding an order at the end of the list
print("Inserted order. Updated orders list: ",orders)
orders.insert(2, "Order6")
print("Inserted order. Updated orders list: ",orders)
print("Cancel an order")
orders.remove("Order2")
print("Updated Orders list: ",orders)

Inserted order. Updated orders list:  ['Order1', 'Order1.b', 'Order2', 'Order3']
Inserted order. Updated orders list:  ['Order1', 'Order1.b', 'Order2', 'Order3', 'Order5']
Inserted order. Updated orders list:  ['Order1', 'Order1.b', 'Order6', 'Order2', 'Order3', 'Order5']
Cancel an order
Updated Orders list:  ['Order1', 'Order1.b', 'Order6', 'Order3', 'Order5']

In [11]:
# deliver the order and remove it from the list
print("Delivering order in queue: ",orders.pop())
print("Delivering priority order: ", orders.pop(2))
print("Pending orders: ", orders)

Delivering order in queue:  Order5
Delivering priority order:  Order6
Pending orders:  ['Order1', 'Order1.b', 'Order3']

In [12]:
orders.append("Order1")
# Duplicate check
seen = list()
for order in orders:

    if order not in seen:
        seen.append(order)
        if orders.count(order)>1:
            print(f"The order {order} is duplicated {orders.count(order)} times")

The order Order1 is duplicated 2 times

In [27]:
student1_marks = [302,902,356,778,834,476,509]

# copy the marks of student 1 to student 2
student2_marks = student1_marks.copy()

# sort to find the first mark
student1_marks.sort()    # ascending
print("First Mark of student 1: ",student1_marks[len(student1_marks)-1])

student1_marks.sort(reverse=True)    # descending
print("First Mark of student 1: ",student1_marks[0])
print("Marks of Student 1: ",student1_marks)
print("Marks of Student 2: ",student2_marks)

First Mark of student 1:  902
First Mark of student 1:  902
Marks of Student 1:  [902, 834, 778, 509, 476, 356, 302]
Marks of Student 2:  [302, 902, 356, 778, 834, 476, 509]

In [28]:
# remove a mark of student 2
student2_marks.remove(902)
print("Marks of Student 1: ",student1_marks)
print("Marks of Student 2: ",student2_marks)

Marks of Student 1:  [902, 834, 778, 509, 476, 356, 302]
Marks of Student 2:  [302, 356, 778, 834, 476, 509]

In [29]:
# remove a mark of student 1
student1_marks.remove(834)
print("Marks of Student 1: ",student1_marks)
print("Marks of Student 2: ",student2_marks)

Marks of Student 1:  [902, 778, 509, 476, 356, 302]
Marks of Student 2:  [302, 356, 778, 834, 476, 509]

Without touching the marks of one student, manipulate the other's

In [30]:
student1_marks = [302,902,356,778,834,476,509]

# assign the marks of student 1 to student 2
student2_marks = student1_marks

# sort to find the first mark
student1_marks.sort()    # ascending
print("First Mark of student 1: ",student1_marks[len(student1_marks)-1])

student1_marks.sort(reverse=True)    # descending
print("First Mark of student 1: ",student1_marks[0])
print("Marks of Student 1: ",student1_marks)
print("Marks of Student 2: ",student2_marks)

First Mark of student 1:  902
First Mark of student 1:  902
Marks of Student 1:  [902, 834, 778, 509, 476, 356, 302]
Marks of Student 2:  [902, 834, 778, 509, 476, 356, 302]

In [31]:
# remove a mark of student 1
student1_marks.remove(834)
print("Marks of Student 1: ",student1_marks)
print("Marks of Student 2: ",student2_marks)

Marks of Student 1:  [902, 778, 509, 476, 356, 302]
Marks of Student 2:  [902, 778, 509, 476, 356, 302]

### Python Datatype - Set

In [32]:
print(orders)

['Order1', 'Order1.b', 'Order3', 'Order1']

In [33]:
# remove duplicate orders
orders = set(orders)
print("Unique orders: ",orders)

Unique orders:  {'Order1', 'Order1.b', 'Order3'}

In [38]:
# unique visitors
block1_visitors = {"Senthil","Rajan"}
print("Existing block 1 visitors: ",block1_visitors)
print("New visitor to 1: Anbu")
block1_visitors.add("Anbu")
print("updated visitors in block 1: ",block1_visitors)

Existing block 1 visitors:  {'Senthil', 'Rajan'}
New visitor to 1: Anbu
updated visitors in block 1:  {'Senthil', 'Rajan', 'Anbu'}

In [39]:
block2_visitors = {"Velu","Guna","Anbu"}
print("Common member to block 1 & 2: ", block2_visitors.intersection(block1_visitors))

Common member to block 1 & 2:  {'Anbu'}

In [40]:
print("All visitors to both the blocks: ",block1_visitors.union(block2_visitors))

All visitors to both the blocks:  {'Senthil', 'Rajan', 'Anbu', 'Guna', 'Velu'}

In [44]:
head_block = {"Rajan","Chandra"}
print("Main head block: ",head_block)

# unsubscribe from one block and add in another
user = head_block.difference(block1_visitors)
print(user," unsubscribed to join block 2")
block2_visitors.update(user)
print("updated visitors in block 1: ",block2_visitors)

Main head block:  {'Rajan', 'Chandra'}
{'Chandra'}  unsubscribed to join block 2
updated visitors in block 1:  {'Anbu', 'Velu', 'Guna', 'Chandra'}

### Python Datatype - Tuple

In [46]:
# employee records
employees = ("Tyrion","Sansa","Arya","John")
print("Employees: ",employees)

Employees:  ('Tyrion', 'Sansa', 'Arya', 'John')

In [48]:
# check serving experience
print("Experience of Tyrion is: ",(len(employees)-employees.index("Tyrion")))
print("Experience of Arya is: ",(len(employees)-employees.index("Arya")))

Experience of Tyrion is:  4
Experience of Arya is:  2

In [52]:
print("Mid experienced employees: ",employees[1:len(employees)-1])

Mid experienced employees:  ('Sansa', 'Arya')

In [58]:
print("Fresher to experienced order: ",employees[::-1])
print("Only expericed employees: ",employees[:len(employees)-1])

Fresher to experienced order:  ('John', 'Arya', 'Sansa', 'Tyrion')
Only expericed employees:  ('Tyrion', 'Sansa', 'Arya')

### Python Datatype - Dictionary

In [71]:
# company employee records
employee1 = {
    "name": "John",
    "salary": 50000,
    "role": "Admin"
}

print(employee1['name'])

John

In [72]:
# Increment to employee1
employee1['salary'] = 100000
print(f"Salary of {employee1['name']} incremented as {employee1['salary']}")

Salary of John incremented as 100000

In [73]:
employee2 = {
    "name": "Peter",
    "salary": 60000,
    "role": "Dev"
}
print("Details of employee2: ",employee2.values())

Details of employee2:  dict_values(['Peter', 60000, 'Dev'])

In [74]:
# add info to employees

employee2["location"] = "Chennai"
employee1["location"] = "Pune"

print(f"Employees updated info: \n{employee1}\n{employee2}")

Employees updated info:
{'name': 'John', 'salary': 100000, 'role': 'Admin', 'location': 'Pune'}
{'name': 'Peter', 'salary': 60000, 'role': 'Dev', 'location': 'Chennai'}

In [75]:
employee1.setdefault("type","probation")
employee2.setdefault("type","permanent")

print(f"Employees current status:\n"
      f"{employee1['name']} is {employee1['type']}\n"
      f"{employee2['name']} is {employee2['type']}"
      )

# promoting employee1
employee1["type"] = "permanent"
print(f"Employees current status:\n"
      f"{employee1['name']} is {employee1['type']}\n"
      f"{employee2['name']} is {employee2['type']}"
      )

Employees current status:
John is probation
Peter is permanent
Employees current status:
John is permanent
Peter is permanent

In [76]:
employee3 = {'name': 'Emily', 'salary': 103000, 'role': 'Hospitality', 'location': 'Kochi','type':'permanent'}
print(f"Employees current status:\n"
      f"{employee1['name']} is {employee1['type']}\n"
      f"{employee2['name']} is {employee2['type']}\n"
      f"{employee3['name']} is {employee3['type']}"
      )
# employee2 resigned
employee2.pop("type")

def checkEmployeeStatus(emp):
    if "type" in emp.keys():
        print(f"The employee '{emp['name']}' is working.")
    else:
        print(f"The employee '{emp['name']}' has resigned.")

checkEmployeeStatus(employee1)
checkEmployeeStatus(employee2)
checkEmployeeStatus(employee3)

Employees current status:
John is permanent
Peter is permanent
Emily is permanent
The employee 'John' is working.
The employee 'Peter' has resigned.
The employee 'Emily' is working.

# Pandas Dataframe from Dictionary

In [77]:
import pandas as pd

In [78]:
employeeData = pd.DataFrame(data=[employee1,employee2,employee3])
employeeData

    name  salary         role location       type
0   John  100000        Admin     Pune  permanent
1  Peter   60000          Dev  Chennai        NaN
2  Emily  103000  Hospitality    Kochi  permanent

In [80]:
orders = {
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006],
    "customer": ["Raj", "Anita", "Karthik", "Priya", "Vikram", "Meena"],
    "product": ["Laptop", "Phone", "Headphones", "Tablet", "Monitor", "Keyboard"],
    "quantity": [1, 2, 1, 1, 2, 3]
}
onlineOrders = pd.DataFrame(data=orders)
onlineOrders

   order_id customer     product  quantity
0      1001      Raj      Laptop         1
1      1002    Anita       Phone         2
2      1003  Karthik  Headphones         1
3      1004    Priya      Tablet         1
4      1005   Vikram     Monitor         2
5      1006    Meena    Keyboard         3

In [81]:
shipping = {
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006],
    "city": ["Chennai", "Bangalore", "Hyderabad", "Mumbai", "Chennai", "Pune"],
    "shipping_cost": [250, 180, 120, 200, 220, 80],
    "status": ["Delivered", "In Transit", "Delivered", "Pending", "Delivered", "In Transit"]
}
deliveryInfo = pd.DataFrame(shipping)
deliveryInfo

   order_id       city  shipping_cost      status
0      1001    Chennai            250   Delivered
1      1002  Bangalore            180  In Transit
2      1003  Hyderabad            120   Delivered
3      1004     Mumbai            200     Pending
4      1005    Chennai            220   Delivered
5      1006       Pune             80  In Transit